#! /bin/bash

set -e

sed -i "s;@SECTION@;${SECTION:+$SECTION/};g" debian/control
sed -i "s;@LIBXDXCT_CONTAINER_TOOLS_VERSION@;${LIBXDXCT_CONTAINER_TOOLS_VERSION:+$LIBXDXCT_CONTAINER_TOOLS_VERSION};g" debian/control
sed -i "s;@VERSION@;${VERSION:+$VERSION};g" debian/control

if [ -n "$DISTRIB" ]; then
    sed -i "s;UNRELEASED;$DISTRIB;" debian/changelog
fi
