#!/bin/sh

set -e

XDXCT_CONTAINER_RUNTIME_HOOK=/usr/bin/xdxct-container-runtime-hook
XDXCT_CONTAINER_TOOLKIT=/usr/bin/xdxct-container-toolkit

case "$1" in
    purge)
        [ -L "${XDXCT_CONTAINER_TOOLKIT}" ] && rm ${XDXCT_CONTAINER_TOOLKIT}
    ;;

    upgrade|failed-upgrade|remove|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
